#!/bin/bash

set -e

if [[ -n "$SWIFTNAV_VERBOSE_TOOLCHAIN" ]]; then
  set -x
fi

NAME=$(basename "$0")
TOOLCHAIN_BINDIR=external/x86_64_linux_gcc_arm_embedded_toolchain/bin

exec "${TOOLCHAIN_BINDIR}"/"${NAME}" "$@"
