#!/bin/bash

set -eux

NAME=$(basename "$0")
TOOLCHAIN_BINDIR=external/x86_64-linux-llvm-distribution/bin

if [[ -f "${TOOLCHAIN_BINDIR}"/"${NAME}" ]]; then
  exec "${TOOLCHAIN_BINDIR}"/"${NAME}" "$@"
elif [[ "${BASH_SOURCE[0]}" == "/"* ]]; then
  execroot_path="${BASH_SOURCE[0]%/*/*/*/*/*/*}"
  tool="${execroot_path}/external/x86_64-linux-llvm-distribution/bin/${NAME}"
  exec "${tool}" "${@}"
else
  >&2 echo "ERROR: could not find ${NAME}; PWD=\"$(pwd)\"; PATH=\"${PATH}\"."
  exit 5
fi

